### ISSUE TITLE
launchctl bootstrap does not work on iOS 16

### ISSUE THREAD

**Issue by opa334** [ProcursusTeam/launchctl#5]
The command

`launchctl bootstrap system /Library/LaunchDaemons`

does not work on iOS 16.2 palera1n, the Loader app does it here https://github.com/palera1n/loader/blob/b0a88c0f07a92db5588a2d9298445fcac95c1afb/palera1nLoader/SettingsSheetView.swift#L93 and that's the reason why the "Launch Daemons" option is broken when on this launchctl version.

What I did notice however that some deamons like frida-server still work, it seems to be isolated to some specific daemons such as opensshd. Running `launchctl load` on the plist manually makes it work though.

No idea if the command works on other iOS versions.

**Comment by CRKatri** [comment]
Just pushed a commit that should fix this, could you give it a test?

**Comment by opa334** [comment]
have tested the build you previously sent a lot and it works fine (please push a release so the palera1n repo can update too?)
