### ISSUE TITLE
Services with `LimitLoadToSessionType` cannot be loaded on iOS 16

### ISSUE THREAD

**Issue by ghost** [ProcursusTeam/launchctl#9]
An example is Frida from https://build.frida.re.

```
iPhone:~ root# launchctl load /Library/LaunchDaemons/re.frida.server.plist 
/Library/LaunchDaemons/re.frida.server.plist: Service cannot load in requested session
```

Removing this from the plist fixes it:
```xml
    <key>LimitLoadToSessionType</key>
    <string>System</string>
```

Tested on 1:1.0.1, not sure if it's been fixed since.

**Comment by CRKatri** [comment]
The iOS 16 simulator's `launchctl` behaves the same way, so I believe this is expected behavior, not a bug.

**Comment by ghost** [comment]
It does sound like a bug to me. The service *is* being loaded in a system session. I don't think exact bug compatibility with Apple's launchctl should be a goal, especially where it provides no value.

**Comment by CRKatri** [comment]
1. 1:1 compatibility with Apple's launchctl is our goal
2. This is not something that `launchctl` can fix, this is a new requirement in `launchd`.

If you want to load the plist: remove `LimitLoadToSessionType` or patch `launchd`.
